service: services

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  deploymentBucket:
    name: allinone-aws-repo
    serverSideEncryption: AES256
  versionFunctions: true

# Lambdas
functions:
  PostgresConnector:
    name: postgres-connector-${self:provider.stage}
    description: An AWS Lambda function processing connection on RDS - Postgres
    handler: postgres/connector.handler
    environment:
      RDS_HOST: xxxxxx
      RDS_USER: xxxxxx
      RDS_PWD: xxxxx
      RDS_DB: xxxx
    runtime: python3.7
    memorySize: 128
    timeout: 60
    role: ConnectorRole
    tags:
      kind: poc
      description: connector to rds postgres

  AuroraConnector:
    name: aurora-connector-${self:provider.stage}
    description: An AWS Lambda function processing connection on RDS - Aurora
    handler: aurora/connector.handler
    environment:
      RDS_HOST: xxxxxx
      RDS_USER: xxxxxx
      RDS_PWD: xxxxx
      RDS_DB: xxxx
    runtime: python3.7
    memorySize: 128
    timeout: 60
    role: ConnectorRole
    tags:
      kind: poc
      description: connector to rds aurora

resources:
  Resources:
    ConnectorRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:provider.stage}-rds-connector-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:
  PostgresConnectorARN:
    Description: ARN of the lambda used to process connection on RDS - Postgres
    Value: !GetAtt [PostgresConnector, Arn]
    Export:
      Name: ${self:service}:${opt:stage}:PostgresConnectorARN

  AuroraConnectorARN:
    Description: ARN of the lambda used to process connection on RDS - Aurora
    Value: !GetAtt [AuroraConnector, Arn]
    Export:
      Name: ${self:service}:${opt:stage}:AuroraConnectorARN
